name: CI

on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install
      - name: Test
        run: pnpm test
      - name: Publish to Visual Studio Marketplace
        if: |
          github.repository == 'callmephilip/html2ft' &&
          startsWith(github.ref, 'refs/tags/')
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          packagePath: ./packages/vscode-html2ft
          dependencies: false
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com